/**
 * Maintenance script: deduplicates each data file and tops up any category
 * that falls below 1000 unique words.
 *
 * Run from repo root: node scripts/expand-words.js
 */
'use strict';
const fs = require('fs');
const path = require('path');

// ---------------------------------------------------------------------------
// Additional words to pad categories that need more entries after dedup
// ---------------------------------------------------------------------------
const additions = {

  places: [
    // Australasian cities
    'Melbourne','Brisbane','Perth','Adelaide','Darwin','Hobart','Canberra',
    'Auckland','Wellington','Christchurch','Dunedin','Queenstown',
    // Eastern European cities
    'Kyiv','Lviv','Kharkiv','Odesa','Minsk','Chisinau','Tiraspol',
    'Riga','Tallinn','Vilnius','Sofia','Bucharest','Zagreb','Ljubljana',
    'Skopje','Tirana','Podgorica','Pristina','Bishkek','Dushanbe',
    'Yekaterinburg','Novosibirsk','Omsk','Irkutsk','Khabarovsk','Magadan',
    // More place types
    'floating market','night market','Sunday market','car boot sale','boot fair',
    'science museum','natural history museum','war museum','folk museum','open-air museum',
    'underground city','cave dwelling','cliff dwelling','pueblo',
    'longhouse village','tent city','floating village',
    'monastery island','desert monastery','mountain monastery','forest hermitage',
    'abandoned resort','ghost resort','derelict hotel',
    // Modern / niche place types
    'geodesic dome','earthship community','shipping container village','tiny house village',
    'coliving space','coworking hub','makerspace','hackerspace','startup garage',
    'data center campus','server farm','nuclear bunker','fallout shelter','community garden',
    'allotment plot','rooftop garden','sky garden','vertical garden wall','pocket park',
    'parklet','living wall','fog garden','desert botanical garden','alpine botanical garden',
    'cactus garden','succulent greenhouse','orchid house','carnivorous plant nursery',
    'mushroom farm tunnel','truffle forest','saffron field',
  ],

  transportation: [
    // More car types
    'compact car','city car','micro car','subcompact','kei car',
    'tow truck','recovery truck','breakdown truck','crane truck',
    'aerial work platform','knuckle boom truck','side loader truck',
    'rear loader truck','front loader truck',
    'logging truck','chip truck','silage truck','grain truck',
    // More aircraft
    'regional turboprop','narrow-body airliner','wide-body airliner',
    'island hopper plane','floatplane','ski-equipped plane','tundra tire plane',
    'solar-powered airplane','hydrogen airplane','electric airplane',
    'crop duster biplane','airshow biplane','aerobatic plane','banner tow plane',
    'skydiving jump plane','wildfire water bomber','fire retardant plane',
    'police fixed-wing','border patrol aircraft','fisheries patrol plane',
    'high-altitude platform station','project loon balloon','stratospheric glider',
    // More boats
    'keelboat','centerboarder','daysailer','weekender','racer-cruiser',
    'motorsailer','bluewater cruiser','circumnavigation yacht',
    'patrol vessel','border patrol boat','harbor patrol boat',
    'customs patrol boat','coast guard buoy tender',
    'water taxi','foot passenger ferry','vehicle ferry','train ferry',
    'pontoon bridge transport','floating bridge crossing',
    // Lorries / vans
    'articulated lorry','refrigerated lorry','flatbed lorry','curtain-sided lorry',
    'box van','luton van','panel van','transit van','sprinter van',
    'cage van','welfare van','catering van',
    // Micro mobility
    'self-balancing scooter','one-wheel electric board','air wheel',
    'electric skateboard','adult kick scooter',
    // Snow / ice
    'Nordic skis','telemark skis','cross-country skis','ski jump skis',
    'race skis','kite ski',
    // Human-powered exotic
    'pedicab','cycle taxi','tricycle taxi','auto-rickshaw',
    'bullock cart','buffalo cart','camel cart','elephant howdah',
    'yak pack train','llama pack','mule train',
    // Party / novelty
    'party bike','conference bike','pub cycle','quadricycle',
    'five-person pedal car','pedal-powered boat',
    // Underwater
    'diver propulsion vehicle','underwater scooter','sea-bob','SEAL delivery vehicle',
    'bathysphere','Alvin deep-sea sub','Shinkai 6500','Trieste bathyscaphe',
    'aqua bike','water bike',
    // Future and maglev
    'hyperloop capsule','vactrain','evacuated tube transport',
    'autonomous last-mile pod','cargo delivery drone',
    'VTOL air taxi','electric VTOL','air mobility vehicle',
    'nuclear-powered icebreaker','ammonia-powered ship','hydrogen ferry',
    'magnetic levitation vehicle','atmospheric railway','pneumatic railway',
    // Historical / exotic
    'horse omnibus','horse tram','horse bus','covered wagon','Conestoga wagon',
    'buckboard','prairie schooner','mail coach','post chaise','diligence coach',
    'troika (three-horse sleigh)','reindeer sleigh','sled dog team (racing)',
    'Venetian gondola','Swiss postal bus','Glacier Express rail car',
    'Bernina Express train','Rocky Mountaineer rail car','Indian Pacific train',
    'Spirit of the Outback train','Caledonian Sleeper','Nightjet overnight train',
    'Venice Simplon-Orient-Express','Blue Train South Africa','Pride of Africa train',
    'Trans-Mongolian train','Trans-Manchurian train','Silk Road train',
    'catamaran hydrofoil','wave-piercing catamaran','surface effect ship',
    'ekranoplan','ground effect vehicle',
    // Fantasy / fictional
    'magic carpet','enchanted broomstick','flying horse','dragon mount',
    'gryphon mount','hippogriff','phantom ship','ghost ship',
    'cursed galleon','enchanted vessel','ship-in-a-bottle (magically enlarged)',
    'chariot of the gods','cloud-chariot','lightning-bolt chariot','winged sandals',
    // Submarine types
    'nuclear-powered submarine','ballistic missile sub','guided missile sub',
    'special operations sub','diesel-electric submarine','AIP submarine',
    'midget submarine','dry combat submersible','swimmer delivery vehicle',
    // Spacecraft (more)
    'commercial space station shuttle','suborbital rocket plane',
    'lunar transfer vehicle','Mars transit habitat','deep space habitat ship',
    'interplanetary cruise ship','von Neumann probe spacecraft','light sail probe',
    // Medical / emergency transport
    'air ambulance','medevac helicopter','critical care transport helicopter',
    'patient transport van','neonatal transport incubator ambulance',
    // More watercraft
    'dugout canoe','birchbark canoe','outrigger canoe','proa sailing vessel',
    'flying proa','waka hourua (Polynesian double hull)','drua (Fijian outrigger)',
    'reed boat','papyrus boat','coracle','bull boat',
    'inflatable rescue boat','RIB (rigid inflatable boat)',
    'submersible yacht','drillship','pipe-laying vessel',
    'cable-laying ship','research vessel','oceanographic ship','ice-breaking research ship',
    // More aircraft
    'gyroplane','autogyro','gyrocopter','ultralight aircraft','microlight',
    'powered hang glider','powered paraglider','paramotor','powered wingsuit',
    'flying car prototype','roadable aircraft',
    'solar-powered drone','hydrogen fuel cell aircraft',
    'agricultural spray helicopter',
    'flying crane helicopter','skycrane helicopter',
    'aerial survey plane','photo reconnaissance plane',
    'tanker aircraft (refueling)','stratospheric research balloon',
    'radiosonde weather balloon',
    // More bicycles (historical)
    'penny-farthing bicycle','velocipede','hobby horse (draisine)','boneshaker bicycle',
    'recumbent bicycle','hand cycle','arm-powered cycle',
    // Novelty / sport
    'ice yacht','ice boat (sailing)','kite buggy','land kite board',
    'sand yacht','land yacht',
    'amphibious bus','amphibious car','amphibious ATV','swamp buggy',
    // Future / space (more)
    'lunar rover','Mars rover','planetary exploration rover',
    'nuclear pulse drive rocket','ion thruster spacecraft',
    'space elevator car','orbital ring transport',
    'tether satellite transport','cycler spacecraft',
    'inflatable space habitat module','rotating torus space station',
    // Animal-powered (more)
    'pack horse train','ox cart','water buffalo cart',
    'elephant logging sled','reindeer pulka sled',
    'camel caravan','llama trek pack animal',
    // Final top-up
    'pedalo boat','swan pedalo','human-powered hydrofoil','water tricycle',
    'cargo bicycle','freight tricycle','urban cargo bike','longtail cargo bike',
    'four-wheeled bicycle','sociable cycle','tandem recumbent',
    'handcar (railway)','velocar','rail bicycle','draisine (motorized)',
    'pedicab (extended)','tuk-tuk (electric)','e-rickshaw',
  ],

  food: [
    // Iberian
    'pintxos','pa amb tomàquet','calçots with romesco','boquerones en vinagre',
    'gambas al ajillo','pulpo a la gallega','caldo verde','bacalhau à Brás',
    'bacalhau com natas','carne de porco à Alentejana','pastel de nata',
    'cataplana','açorda','migas',
    // African
    'bobotie','potjiekos','biltong','droëwors','melktert','koeksisters','malva pudding',
    'jollof rice','egusi soup','ogbono soup','moi moi','akara','puff puff (Nigerian)',
    'nkwobi','ugba',
    'kitfo','tibs','doro wat','misir wat','gomen','ayib',
    'tagine (lamb)','rfissa','tanjia','kefta tagine',
    // Ethiopian
    'injera with berbere stew','shiro','ful medames Egyptian style',
    // American regional
    'Creole gumbo','shrimp Creole','red beans and rice','boudin sausage',
    'king cake','Brunswick stew','Kentucky burgoo','hoppin John',
    'Virginia ham','Philadelphia scrapple','New England baked beans','Boston brown bread',
    'Cincinnati five-way chili','Cleveland Polish boy','Michigan hot dog',
    'Detroit coney dog','Chicago Italian beef','St. Louis toasted ravioli',
    'Kansas City burnt ends','Oklahoma fried onion burger',
    'California fish taco','Sonoran hot dog','New Mexico green chile stew',
    'Hawaii loco moco','Hawaiian musubi','Spam musubi','plate lunch','poi','kalua pork',
    // Caucasian
    'khachapuri','khinkali','churchkhela','badrijani nigvzit','pkhali',
    'Armenian dolma','Armenian harissa','Azerbaijani plov','Uzbek lagman',
    'Kazakh beshbarmak','Kyrgyz manti',
    // Middle Eastern additions
    'Palestinian musakhan','Iraqi masgouf','Yemeni saltah','Yemeni fahsa',
    'Persian ghormeh sabzi','Persian fesenjan','Persian zereshk polo','Persian tahdig',
    'Persian ash reshteh','Persian faloodeh','Persian bastani',
    // Indian additions
    'kulfi','rabri','malpua','shrikhand','halwa','sooji halwa','gajar halwa',
    'besan ladoo','motichoor ladoo','chakli','murukku','gathiya','fafda',
    'falooda',
    // South / Southeast Asian
    'Sri Lankan hoppers','Sri Lankan string hoppers','pol sambol','kottu roti','Sri Lankan milk rice',
    'Burmese mohinga','Burmese laphet thoke','Cambodian amok','num banh chok',
    'Laotian khao niao','Laotian tam mak hoong','Vietnamese xôi',
    'Malaysian nasi lemak','Malaysian roti canai',
    'Singaporean chilli crab','Singaporean char kway teow',
    // Japanese additions
    'tonkotsu broth','tonkatsu sauce','mentaiko','ikura','uni','tamago sushi',
    'chirashi bowl','kaiseki','kappo cuisine','obanzai','osechi ryori',
    'miso glazed black cod','miso soup with tofu','chawanmushi steamed egg',
    // Chinese additions
    'Peking duck pancake wrap','twice-cooked pork belly','dong po rou','hong shao rou',
    'Chongqing noodles','Yunnan cross-bridge noodles','Shanghainese soup dumpling',
    'xiao long bao','sheng jian bao','guo tie','zha jiang mian','dan dan noodles',
    // Korean additions
    'Korean fried chicken','ganjang gejang','mul naengmyeon','bibim naengmyeon',
    'samgyetang','seollongtang','tang suyuk','japchae glass noodles',
    'gamjatang','kongguksu','dongchimi','ggakdugi','oiji pickle',
    // European additions
    'Scotch egg','scotch broth','haggis','cock-a-leekie','cullen skink',
    'Bakewell tart','Eccles cake','Yorkshire pudding','toad in the hole',
    'Welsh rarebit','laverbread','bara brith','Irish soda bread','boxty',
    'Belgian carbonnade flamande','Belgian waterzooi','Dutch erwtensoep',
    'Dutch stamppot','Norwegian fårikål','Swedish janssons frestelse',
    'Danish smørrebrød','Finnish reindeer stew','Estonian kama','Latvian grey peas',
    'Polish bigos','Polish żurek','Czech svíčková','Slovak bryndzové halušky',
    'Hungarian goulash','Hungarian lángos','Romanian mămăligă','Bulgarian banitsa',
    'Greek spanakopita','Greek pastitsio','Greek stifado','Greek fava dip',
    'Italian ribollita (already deduped via script)','Sardinian porceddu',
    'Ligurian pesto trofie','Pugliese orecchiette with broccoli rabe',
    'Sicilian arancini (caponata version)','Venetian bacalà mantecato',
    'Milanese cotoletta','Florentine bistecca','Roman cacio e pepe',
    // Desserts / sweets additions
    'German Bienenstich','Austrian Kaiserschmarrn',
    'Swiss Vermicelles','Dutch poffertjes (extra)','Belgian liège waffle',
    'English syllabub','British Eton mess','trifle with sherry',
    'Scandinavian kladdkaka','Norwegian lefse','Swedish semlor',
    'Finnish munkki donut','Danish æbleskiver','Polish chrusciki',
    'Greek loukoumades','Cypriot daktyla','Lebanese knefe (kunafa)',
    'Egyptian basbousa semolina (deduped variant: orange blossom basbousa)',
    'Moroccan chebakia','Algerian makroud','Tunisian bambalouni',
    'Indian jalebi in rabri','Pakistani gulab jamun kheer',
    'Bangladeshi mishti doi','Sri Lankan watalappan',
    'Malaysian kuih lapis','Indonesian klepon','Filipino bibingka',
  ],

  animals: [
    // Fish
    'Atlantic cod','Pacific cod','haddock','pollock','hake','whiting','coalfish',
    'monkfish','John Dory','Dover sole','lemon sole','plaice','flounder','turbot','brill',
    'swordfish','marlin','sailfish','wahoo','mahi-mahi','amberjack','yellowtail kingfish',
    'tarpon','bonefish','barracuda','needlefish','flying fish','mudskipper',
    'archerfish','pufferfish','porcupinefish','boxfish','cowfish','filefish','triggerfish',
    'surgeonfish','tang','unicornfish','moorish idol','butterflyfish (coral reef)',
    'clownfish','damselfish','chromis','anthias','wrasse','parrotfish','grouper',
    'coelacanth','lungfish','bichir','alligator gar','paddlefish','beluga sturgeon',
    'arowana','arapaima','pirarucu','electric eel','knifefish','ghost knifefish',
    'piranha','payara','catfish','wels catfish','mekong giant catfish','pangasius',
    'tench','bream','roach','rudd','bleak','dace','chub','barbel','asp',
    'minnow','gudgeon','loach','stone loach','spined loach','weather loach',
    'grayling','brown trout','rainbow trout','brook trout','lake trout','bull trout',
    'Atlantic salmon','Pacific salmon','Chinook salmon','sockeye salmon','coho salmon',
    'pink salmon','chum salmon','cherry salmon','huchen','taimen',
    // Birds (more)
    'shoebill stork','whale-headed stork','hammerkop','boat-billed heron',
    'night heron','zigzag heron','capped heron','striated heron',
    'superb starling','wattled starling','metallic starling','shining starling',
    'hoopoe','green wood hoopoe','great hornbill','rhinoceros hornbill','wreathed hornbill',
    'sun conure','jenday conure','nanday conure','golden conure',
    'yellow-headed amazon parrot','blue-fronted amazon','lilac-crowned amazon',
    'kea parrot','kākā parrot','rainbow lorikeet','musk lorikeet',
    'ribbon-tailed astrapia','magnificent bird-of-paradise','Wilson\'s bird-of-paradise',
    'twelve-wired bird-of-paradise','Lawes\'s parotia','Wahnes\'s parotia',
    'cassowary','southern cassowary','northern cassowary','dwarf cassowary',
    'emu','greater rhea','lesser rhea','Darwin\'s rhea','ostrich',
    'tinamou','great tinamou','elegant crested tinamou','variegated tinamou',
    'sunbittern','kagu','takahē','takahe (flightless)','weka','kokako',
    'wrybill','black stilt','pied stilt','shore plover','stitchbird','hihi',
    'saddleback bird','rifleman (bird)','New Zealand wren','rock wren (NZ)',
    // More insects
    'stag beetle','fire beetle','bombardier beetle','click beetle','firefly','glowworm',
    'dung beetle','scarab beetle','tiger beetle','whirligig beetle','great diving beetle',
    'dragonfly','damselfly','green darner dragonfly','emperor dragonfly',
    'painted lady butterfly','red admiral butterfly','common swallowtail',
    'giant swallowtail','glasswing butterfly','owl butterfly','dead leaf butterfly',
    'lacewing','antlion','dobsonfly','fishfly','hellgrammite',
    'cicada','periodical cicada','giant cicada','flatid planthopper','lanternfly',
    'assassin bug','wheel bug','ambush bug','water strider','giant water bug',
    'cave cricket','Jerusalem cricket','mole cricket','camel cricket',
    'vinegaroon','whip scorpion','wind scorpion','sun spider','camel spider',
    'harvestman','daddy longlegs spider','trapdoor spider','purse web spider',
    'orb weaver spider','golden silk orb weaver','garden spider','grass spider',
    // Reptiles / amphibians (more)
    'Burmese star tortoise','radiated tortoise','pancake tortoise',
    'African spurred tortoise','Hermann\'s tortoise','red-footed tortoise',
    'green tree monitor','peach-throated monitor','mangrove monitor','water monitor',
    'Meller\'s chameleon','Namaqua chameleon','flap-necked chameleon','carpet chameleon',
    'spitting cobra','monocled cobra','Mozambique spitting cobra','forest cobra',
    'vine snake','blunt-headed tree snake','cat-eyed snake','cat snake',
    'Surinam horned frog','Pacman frog','ornate horned frog','Colombian horned frog',
    'African clawed frog','Surinam toad','hairy frog','tomato frog','desert rain frog',
    // Unusual creatures
    'velvet worm','horseshoe worm','peanut worm','ribbon worm','acorn worm',
    'water bear (extended)','sea spider','pycnogonid','tardigrade (extended)',
    'sea mouse worm','fire worm','Christmas tree worm (extended)','peacock worm (extended)',
    'giant African millipede','pill millipede','flat-backed millipede','bristly millipede',
    'centipede','giant centipede','Amazonian giant centipede','Vietnamese centipede',
    'scolopendra','house centipede','stone centipede','soil centipede',
  ],

  occupations: [
    // Academic
    'professor','associate professor','assistant professor','lecturer','research fellow',
    'postdoctoral researcher','lab technician','grants administrator','technology transfer officer',
    // Healthcare additions
    'nurse anesthetist','flight nurse','school nurse','industrial nurse','prison nurse',
    'doula','lactation consultant','postpartum nurse','neonatal nurse',
    'genetic counselor','wound care nurse','dialysis technician','medical device rep',
    'perfusionist','surgical technologist','sterile processing technician',
    'medical transcriptionist','medical coder','medical biller','health information manager',
    // Legal / government additions
    'immigration officer','border control officer','passport control officer','visa officer',
    'employment tribunal judge','bankruptcy judge','immigration judge','traffic court judge',
    'traffic warden','parking enforcement officer','building inspector',
    'fire marshal','health inspector','food safety inspector','OSHA inspector',
    'tax collector','IRS agent','SEC investigator','financial crimes investigator',
    'certified public accountant','management accountant','cost accountant',
    'forensic accountant','tax preparer','enrolled agent','estate planner','financial advisor',
    // Engineering
    'civil engineer','structural engineer','geotechnical engineer','traffic engineer',
    'environmental engineer','water resources engineer','sanitary engineer',
    'electrical engineer','power systems engineer','control systems engineer',
    'embedded systems engineer','RF engineer',
    'mechanical engineer','thermal engineer','fluid mechanics engineer','manufacturing engineer',
    'quality engineer','aerospace engineer','propulsion engineer','aeronautics engineer',
    'structures engineer','composites engineer',
    'naval architect','marine engineer','shipbuilding engineer','offshore engineer','subsea engineer',
    'mining engineer','petroleum engineer','drilling engineer','reservoir engineer',
    'nuclear engineer','health physics specialist','radiation protection officer',
    'biomedical engineer','clinical engineer','rehabilitation engineer',
    'orthotics technician','prosthetics technician',
    // Skilled trades additions
    'plumber','pipefitter','steamfitter','gasfitter','drainlayer',
    'electrician','journeyman electrician','master electrician','wireman','lineman',
    'HVAC technician','refrigeration technician','boilermaker','sheet metal worker',
    'glazier','window fitter','solar panel installer',
    'flat roofer','slate roofer','guttering installer','fascia board fitter',
    'scaffolder','rigger','formwork carpenter','reinforcing steel fixer','concrete finisher',
    'demolition worker','blaster','explosives technician','steeplejack','tower climber',
    'wind turbine technician','elevator installer','escalator technician',
    // Creative / media additions
    'radio presenter','radio DJ','podcast producer','audio engineer','broadcast engineer',
    'television presenter','news anchor','sports commentator','weather presenter','game show host',
    'reality TV producer','documentary filmmaker','short film director',
    'music video director','commercial director','animation director',
    'character animator','background artist','layout artist','cleanup artist',
    'inbetweener (animation)','cel painter','digital colorist','3D modeler',
    'texture artist (3D)','lighting artist (3D)','rigging artist','effects artist',
    'crowd simulation artist','environment artist','level designer',
    'game designer','narrative designer',
    // Food service additions
    'head chef','sous chef','chef de partie','commis chef','pastry sous chef',
    'cold kitchen chef','grill chef','fry cook','short order cook','breakfast cook','banquet cook',
    'catering manager','catering assistant','kitchen porter','pot washer',
    'waiter','server','senior waiter','head waiter','floor manager','restaurant manager',
    'maître d','host (restaurant)','busboy','busser','food runner','barback',
    'cocktail server','bottle service attendant','VIP server',
    // Sports / fitness additions
    'personal trainer','group fitness instructor','yoga instructor','pilates instructor',
    'spin instructor','CrossFit coach','powerlifting coach','Olympic lifting coach',
    'gymnastic coach','cheerleading coach',
    'swim coach','dive coach','water polo coach','rowing coach','sailing instructor',
    'tennis coach','squash coach','badminton coach','table tennis coach','pickleball coach',
    'golf pro','golf caddy','golf course superintendent','greenskeeper',
    'football coach','offensive coordinator','defensive coordinator','special teams coach',
    'strength and conditioning coach','sports physiotherapist','athletic trainer',
    'sports massage therapist','sports psychologist','sports nutritionist',
    'performance analyst','video analyst','scout (sports)','talent scout',
    'sports agent','sports lawyer','boxing trainer',
    'jockey','horse trainer (racing)','equine veterinarian','horse dentist',
    'equine nutritionist','stable hand','groom (horse)',
    // Other
    'freight forwarder','customs broker','import/export specialist','trade compliance officer',
    'logistics coordinator','supply chain manager','warehouse manager','inventory manager',
    'dispatch coordinator','fleet manager','route planner','last-mile delivery manager',
    'cemetery manager','gravedigger','funeral director','embalmer','cremation technician',
    'floral designer','wreath maker','event floral designer','wedding florist',
    'sign painter','sign writer','neon sign maker','vinyl wrap installer','billboard installer',
    'window dresser','visual merchandiser','display artist','retail display designer',
    // Niche / emerging occupations
    'wax figure sculptor','escape room designer','board game designer',
    'puzzle constructor','crossword setter','theme park ride designer',
    'immersive experience creator','haunted house designer','haunt actor',
    'rage room attendant','axe-throwing instructor','paddleboard instructor',
    'freediving instructor','breathwork coach','cold exposure therapist',
    'professional cuddler','professional mermaid performer','professional bridesmaid',
    'curated closet stylist','personal shopper','image consultant',
    'color analyst','reiki practitioner','sound bath facilitator',
    'gong bath practitioner','crystal healer','aura reader',
    'past-life regression therapist','sensory deprivation guide',
  ],

  emotions: [
    // Unusual named emotions
    'acedia','anhedonia','alexithymia','aporia','ataraxia','eudaimonia','dysphoria',
    'irascibility','lassitude','languor','petulance','pique','umbrage','dudgeon',
    'huff','snit','tizzy','chafe','rankle',
    // Hurt and dignity
    'wounded pride','bruised ego','damaged dignity','punctured self-image',
    'shattered confidence','crisis of confidence','imposter syndrome feeling',
    'beginner\'s mind','expert\'s blindness',
    // Work-related emotional states
    'burnout (full)','boreout','compassion fatigue','vicarious trauma',
    'secondary traumatic stress','moral injury','decision fatigue',
    'cognitive overload','analysis paralysis','option paralysis',
    'FOMO','JOMO','FOBO','status anxiety','class anxiety',
    'financial anxiety','health anxiety','relationship anxiety',
    // Attachment and relationship emotions
    'attachment anxiety','avoidant attachment feeling','secure base feeling',
    'safe harbor feeling','home-coming feeling','fish-out-of-water feeling',
    'square-peg feeling','belonging crisis','identity crisis','quarterlife crisis',
    'midlife crisis','purpose crisis','direction crisis','drift feeling',
    'rudderless feeling','anchorless feeling','groundless feeling',
    'vertigo of freedom','paradox of choice feeling','fear of commitment',
    'regret anticipation','pre-emptive nostalgia','anticipatory grief',
    'anticipatory joy','savoring','afterglow','lingering pleasure',
    // Time-of-day / cycle emotions
    'Monday morning feeling','Sunday evening dread','mid-week slump',
    'Friday afternoon buzz','holiday feeling','pre-holiday excitement',
    'post-holiday blues','back-to-school feeling','first-day-of-school feeling',
    'graduation feeling','retirement feeling','new job feeling',
    'imposter feeling (new job)','creative stagnation','writer\'s block feeling',
    'blank canvas feeling',
    // Romantic and social emotions
    'lovesick feeling','unrequited love pain','friendzone feeling',
    'mixed signals confusion','on-again-off-again exhaustion',
    'situationship ambiguity','slow burn tension','butterflies (romantic)',
    'weak in the knees feeling','heart skipping a beat','drunk on love',
    'love bombing feeling','honeymoon phase','first-date jitters',
    // More adjective-form emotion words
    'brooding','dejected','ebullient','exasperated','flummoxed',
    'flustered','frazzled','gobsmacked','haggard','harried',
    'incredulous','indignant','infuriated','jittery','keyed up',
    'livid','miffed','mortified','nettled','overwrought',
    'peevish','perturbed','piqued','placid','poised',
    'rattled','riled','rueful','sheepish','smitten',
    'smug','snippy','sour','spiteful','standoffish',
    'tense','thunderstruck','uneasy','unhinged','unmoored',
    'unnerved','unsettled','vexed','woeful','wretched',
    'yearning (adj)','zealous','zen','zany','zippy',
    // Nuanced positive states
    'accomplished feeling','actualized feeling','aligned feeling','animated feeling',
    'assured feeling','attuned feeling','awakened feeling','balanced feeling',
    'bountiful feeling','bright feeling','buoyant feeling','capable feeling',
    'centered feeling','cherished feeling','clear-headed feeling','clear feeling',
    'composed feeling','confident feeling (calm)','connected feeling','courageous feeling',
    'creative feeling','curious feeling','dazzled feeling','determined feeling',
    'devoted feeling','dignified feeling','emboldened feeling','empowered feeling',
    'energized feeling','engaged feeling','enlightened feeling','enriched feeling',
    'enthusiastic feeling','expansive feeling','expressive feeling','exuberant feeling',
    'faithful feeling','fascinated feeling','fired-up feeling','flourishing feeling',
    'focused feeling','free feeling','fulfilled feeling','generous feeling',
    'gleeful feeling','glowing feeling','graceful feeling','grateful feeling',
    'harmonious feeling','healed feeling','hearty feeling','hopeful feeling',
    'illuminated feeling','imaginative feeling','inquisitive feeling','inspired feeling',
    'integrated feeling','joyful feeling','jubilant feeling','kind-hearted feeling',
    'lively feeling','loved feeling','luminous feeling','majestic feeling',
    'mellow feeling','mindful feeling','motivated feeling','moved feeling',
    'nourished feeling','open feeling','optimistic feeling','overjoyed feeling',
    'passionate feeling','peaceful feeling','playful feeling','plentiful feeling',
    'present feeling','proud feeling','purposeful feeling','radiant feeling',
    'reassured feeling','refreshed feeling','rejuvenated feeling','resilient feeling',
    'restored feeling','revitalized feeling','righteous feeling','rooted feeling',
    'safe feeling','satisfied feeling','serene feeling','settled feeling',
    'soulful feeling','spirited feeling','spontaneous feeling','steadfast feeling',
    'stimulated feeling','strong feeling','tender feeling','thankful feeling',
    'thoughtful feeling','thriving feeling','touched feeling','tranquil feeling',
    'trusting feeling','unburdened feeling','unified feeling','uplifted feeling',
    'validated feeling','vibrant feeling','vital feeling','vulnerable (safe) feeling',
    'warm feeling','whole feeling','willing feeling','wise feeling',
    'wonder feeling','worshipful feeling','worthy feeling',
    // Nuanced negative states
    'abandoned feeling','abashed feeling','agitated feeling','alienated feeling',
    'ambivalent feeling','anguished feeling','apprehensive feeling','ashamed feeling',
    'bitter feeling','bleak feeling','burdened feeling','claustrophobic feeling',
    'crestfallen feeling','crushed feeling','cynical feeling','defeated feeling',
    'deflated feeling','demoralized feeling','despondent feeling','diminished feeling',
    'disconnected feeling','disenchanted feeling','disheartened feeling','dismayed feeling',
    'dispirited feeling','disregarded feeling','dissatisfied feeling','drained feeling',
    'embattled feeling','excluded feeling','exposed feeling','fragile feeling',
    'frantic feeling','frozen feeling','grieving feeling','guarded feeling',
    'haunted feeling','heartbroken feeling','helpless feeling','hollow feeling',
    'hopeless feeling','humbled (painfully) feeling','imprisoned feeling',
    'inconsolable feeling','indifferent feeling','inferior feeling','insignificant feeling',
    'invisible feeling','irritated feeling','isolated feeling','jaded feeling',
    'judgmental feeling','left-out feeling','let-down feeling','listless feeling',
    'lost feeling','marginalized feeling','misunderstood feeling','neglected feeling',
    'nervous feeling','numbed feeling','objectified feeling','oppressed feeling',
    'ostracized feeling','overwhelmed feeling','paralyzed feeling','persecuted feeling',
    'pessimistic feeling','pitied feeling','powerless feeling','pressured feeling',
    'repressed feeling','resigned feeling','restless feeling','self-conscious feeling',
    'self-critical feeling','self-doubting feeling','self-pitying feeling',
    'shamed feeling','silenced feeling','small feeling','smothered feeling',
    'stifled feeling','stuck feeling','suffocated feeling','suspicious feeling',
    'trapped feeling','troubled feeling','unappreciated feeling','uncertain feeling',
    'undervalued feeling','unworthy feeling','used feeling','violated feeling',
    'worthless feeling','wounded feeling',
    // Body-focused emotional states
    'racing heart feeling','tight chest feeling','shallow breath feeling',
    'dry mouth feeling','sweaty palms feeling','trembling feeling',
    'clenched jaw feeling','knotted stomach feeling','weak legs feeling',
    'flushed face feeling','cold sweat feeling','goosebumps feeling (fear)',
    'goosebumps feeling (awe)','chills of excitement','electric anticipation',
    'leaden limbs feeling','heavy eyelids feeling','light body feeling',
    'floating feeling','dissociated feeling','zoned-out feeling','spaced-out feeling',
    'hyper-alert feeling','hyper-vigilant feeling','tunnel vision feeling',
    // Named emotions from other languages
    'Torschlusspanik (gate-closing panic)','Waldeinsamkeit (forest solitude)',
    'Fremdschämen (vicarious embarrassment)','Verschlimmbessern (worsening by improving)',
    'duende (dark artistic inspiration)','morriña (Galician ache for home)',
    'sobremesa feeling (lingering at the table)','fado feeling (Portuguese melancholy)',
    'sprezzatura (effortless grace feeling)','mamihlapinatapai variant',
    'frisson (chills from beauty)','peak experience','oceanic feeling',
    'unitive experience','satori flash','kensho moment','metanoia (transformative shift)',
    // Eco / tech modern emotions
    'eco-anxiety','climate grief','solastalgia (grief for changed landscape)',
    'techno-anxiety','digital overwhelm','notification dread','scroll fatigue',
    'like-seeking compulsion','follower count anxiety','inbox dread',
    'phantom phone vibration feeling','nomophobia feeling (fear of no phone)',
    // Psychological / somatic
    'enmeshment discomfort','codependency awareness','emotional flashback',
    'window of tolerance feeling','somatic release','nervous system reset',
    'parasympathetic ease','sympathetic activation','dorsal vagal freeze',
    'ventral vagal safety','polyvagal connection feeling','titration feeling',
    'hypervigilance (trauma response)',
    // Social / collective
    'collective effervescence','shared grief','communal joy',
    'intergenerational pride','ancestral shame','cultural dissonance',
    'heritage disconnection','diaspora longing','third-culture tension',
    'code-switching exhaustion','cultural homesickness','language grief',
    // Bodily / somatic (more)
    'kinesthetic joy','muscle memory pride','proprioceptive ease',
    'visceral dread','gut-level knowing','bone-deep fatigue',
    'cellular depletion','embodied knowing','felt sense',
    // Creative / aesthetic
    'creative flow state','artistic drought','inspiration hunger',
    'creative birth pangs','aesthetic rapture','musical ecstasy',
    'beauty overwhelm','sublime terror','formless awe',
    // Relational (more)
    'chosen family warmth','found family feeling','soul recognition',
    'platonic love overflow','community belonging','tribal pride',
    'pack bond feeling','heartmate connection',
    // Acceptance / surrender
    'dignified surrender','peaceful acceptance','radical acceptance',
    'loving detachment','compassionate neutrality','equanimity in chaos',
    'stillness under pressure','grace under fire',
    // Ambiguous / liminal
    'moral ambiguity feeling','ethical grey zone discomfort',
    'liminal space feeling','threshold feeling','in-between feeling',
    'not-yet feeling','no-longer feeling','almost-there feeling',
    'past-due feeling','overdue relief','anticipatory exhaustion',
  ],

  actions: [
    // Cooking actions
    'blanching','tempering chocolate','blooming spices','deglazing','flambéing',
    'curing (food)','brining','pickling','fermenting','dehydrating','cold smoking',
    'hot smoking','aging (cheese)','proofing dough','laminating pastry',
    'folding in egg whites','shaping dough','portioning','plating','garnishing',
    // Kitchen technique actions
    'zesting','segmenting citrus','brunoise-cutting','chiffonading','tourné-cutting',
    'barding','larding','trussing','deboning','butterflying (meat)',
    'scoring skin','pricking pastry','blind baking','par-baking','egg washing',
    'brushing with butter','basting','glazing (cooking)','reducing','clarifying butter',
    'making a roux','mounting with butter','finishing with cream','acidulating',
    'seasoning (professional)','tasting and adjusting','checking for seasoning',
    // Sports and athletic actions (more)
    'dead-lifting','clean-and-jerking','snatching (weightlifting)','muscle-upping',
    'kipping pull-upping','strict pressing','push-pressing','jerking overhead',
    'rope climbing','rope descending','box jumping','depth jumping',
    'tire flipping','sled pushing','sled pulling','battle rope waving',
    'kettlebell swinging','kettlebell pressing','goblet squatting','Turkish get-up',
    'wall balling','med ball throwing','med ball slamming','plank holding',
    'L-sit holding','handstand walking','cartwheeling (gymnastics)','round-off',
    'back-handspring','front-tuck','layout (gymnastics)','pike jump','straddle jump',
    // Dance actions (more)
    'waltzing','fox-trotting','quick-stepping','Viennese waltzing','slow foxtrot',
    'paso doblé','samba (ballroom)','rumba','cha-cha-cha','East Coast swing',
    'West Coast swing','lindy hopping','Balboa dancing','collegiate shag',
    'Argentine tango','close embrace tango','open embrace tango','tango milonga',
    'flamenco footwork','zapateado','palmas clapping','castanets playing',
    'bharatanatyam dancing','Odissi dancing','Manipuri dancing','Kuchipudi dancing',
    'Mohiniyattam dancing','Sattriya dancing','kathakali performing','yakshagana',
    'haka performing','poi (Māori)','tītī tōrea (Māori stick game)','kapa haka',
    'capoeira playing','maculelê','samba de roda','candomblé dancing',
    // Movement arts (more)
    'practicing Tai Chi','doing Qigong','performing Wushu','practicing Kung Fu forms',
    'sparring with wooden dummy','practicing kata','drilling bunkai',
    'shadow boxing','heavy bag training','speed bag training','double-end bag training',
    'pad work drilling','mitts training','clinch work','inside fighting',
    'stance switching','footwork drilling','head movement drilling','slipping punches',
    'rolling with punches','parrying punches','catching kicks','checking low kicks',
    // Expressive and social (more)
    'finger-wagging','arm-crossing','foot-tapping (impatience)','ear-pulling',
    'nose-touching','eye-covering','mouth-covering','chin-stroking',
    'brow-furrowing','eye-widening','jaw-dropping','gasping',
    'tutting (disapproval)','huffing','puffing','sighing dramatically',
    'eye-rolling dramatically','staring into the middle distance',
    'looking pointedly at watch','checking phone ostentatiously',
    'drumming fingers impatiently','clearing throat meaningfully',
    'raising one eyebrow','arching an eyebrow','cocking an eyebrow',
    'pursing lips','smirking','grinning broadly','beaming','radiant smiling',
    'scowling','glowering','frowning deeply','pouting',
    // Professional actions
    'filing paperwork','stamping documents','notarizing','witnessing a signature',
    'taking depositions','cross-examining witnesses','delivering closing arguments',
    'objecting in court','overruling','sustaining objections','deliberating',
    'issuing a verdict','passing sentence','signing a treaty','ratifying legislation',
    'vetoing a bill','filibustering','calling a vote','casting a vote',
    'lobbying','canvassing','campaigning','stumping (political)','debating (political)',
    'caucusing','gerrymandering','redistricting','redlining','zoning (urban planning)',
    // Scientific actions
    'centrifuging','pipetting','titrating','chromatographing','spectroscoping',
    'PCR amplifying','gel electrophoresing','Western blotting','Northern blotting',
    'Southern blotting','cell culturing','passaging cells','transfecting',
    'cryopreserving','lyophilizing (freeze drying)','autoclaving','sterilizing',
    'dissecting','fixing (tissue)','embedding','sectioning','staining (microscopy)',
    'mounting slides','coverslipping','imaging','counting cells',
    // Craft and making actions (more)
    'forging metal','annealing','quenching (metallurgy)','tempering (metal)',
    'case hardening','nitriding','carburizing','electroplating','powder coating',
    'galvanizing','tinning','silvering','gilding (metal)','enameling (metal)',
    'repoussé work','chasing (metalwork)','inlaying','damascening','encrusting',
    'chip carving','relief carving','in-the-round carving','whittling (advanced)',
    'turning (lathe)','boring (lathe)','threading (lathe)','knurling',
    'milling','CNC machining','EDM machining','waterjet cutting','laser cutting',
    'plasma cutting','oxy-acetylene cutting','brazing','silver soldering','hard soldering',
    // Outdoor and adventure actions
    'orienteering','navigating by stars','reading topo maps','backcountry navigating',
    'river reading (kayaking)','scouting rapids','portaging','lining a canoe',
    'poling (canoe)','paddling eddy turns','ferrying across current',
    'lead climbing','sport climbing','trad climbing','aid climbing','free soloing',
    'multipitch climbing','big wall climbing','top roping','bouldering problems',
    'downclimbing','downclimbing reversals','stemming','laybacking','crack climbing',
    'slacklining','highlining','waterline slacklining','long-line slacklining',
    'via ferrata climbing','canyoneering','canyoning','canyon rappelling',
    'caving','speleothem documenting','cave diving','sump diving',
    // Improv-gold actions
    'teaching calculus to a parrot','explaining cryptocurrency to an elder',
    'attempting to return an item with no receipt','negotiating with bureaucracy',
    'filling out a very long form','waiting on hold dramatically',
    'parallel parking under pressure','attempting furniture assembly',
    'interpreting modern art',
    'being a tree in a storm','melting very slowly','rebooting like a computer',
    'speaking entirely in questions','narrating everything in third person',
    'performing a documentary about yourself','hosting an imaginary chat show',
    'accepting an award for something trivial','giving a TED talk about nothing',
    'dramatically over-explaining something simple',
  ],

  characters: [
    // More fantasy archetypes
    'hedge wizard','village witch','crone','wise woman','cunning man','wise man',
    'seer (village)','herbalist (magical)','hedge witch','green witch',
    'warden of the forest','keeper of the flame','guardian of the gate',
    'last of the order','sole survivor of the guild','wandering swordsman',
    'disgraced knight','fallen paladin','renegade templar','ex-inquisitor',
    'exiled royalty','disguised noble','hidden heir','rightful king in hiding',
    'foundling with destiny','orphan of prophecy','child of the stars',
    'halfblood wizard','blood mage','soul mage','death mage','void mage','storm mage',
    'runic warrior','rune knight','emblem knight','brand warrior','sigil bearer',
    'golem maker','construct crafter','animated armor warrior','clockwork soldier',
    'illusion weaver','mirror mage','dream walker','shadow dancer','shade',
    'astral projector','ethereal traveler','planar walker','dimensional anchor',
    'abjurer','conjurer','diviner','enchanter','evoker','transmuter','universalist',
    'elementalist','pyromancer','hydromancer','geomancer','aeromancer','cryomancer',
    'biomancer','hemomancer','chronmancer','spacemancer','lumimancer','umbramancer',
    // More sci-fi characters
    'first officer','chief engineer (starship)','tactical officer','chief medical officer',
    'science officer (away team)','communications officer','helmsman (warp)','navigator (warp)',
    'colony founder','terraformer','atmospheric processor tech','biodome engineer',
    'cryogenic technician (sleeper ship)','revival specialist','memory wiper','identity restorer',
    'uplift worker','sentience researcher','AI rights lawyer','digital consciousness advocate',
    'body hopper','consciousness pirate','mind thief','memory dealer','dream harvester',
    'corporate assassin (cyber)','megacorp fixer','zaibatsu agent','consortium enforcer',
    'street-level doc','ripperdoc','black market surgeon','illegal augmentation specialist',
    'memory fence','stolen experience dealer','sensory recording pirate',
    'interstellar diplomat','first contact protocol officer','xenolinguist','cultural translator',
    'alien artifact smuggler','pre-cursor relic black market dealer','void archaeologist',
    'star map thief','navigation data broker','jump route seller',
    // More historical character types
    'Sengoku warlord','daimyo (warring states)','ashigaru (foot soldier)','ikki (peasant rebel)',
    'Crusader knight','Saracen warrior','Byzantine cataphract','Varangian Guard member',
    'Numidian cavalry rider','Macedonian phalangite','Spartan hoplite','Athenian trireme captain',
    'Roman legionnaire','Roman centurion','Roman auxiliary','Germanic barbarian chieftain',
    'Mongol horseman','Mongol archer','Mongol shaman','great khan\'s envoy',
    'Ottoman sipahi','Ottoman janissary','Ottoman vizier','grand vizier','pasha',
    'Aztec Eagle warrior','Aztec Jaguar warrior','Aztec priest (Huitzilopochtli)',
    'Aztec merchant (pochteca)','Aztec spy','Aztec tribute collector',
    'Inca Inca-Capac','Inca tambocamayoc','Inca quipucamayoc','Inca army general',
    'Mayan ballgame player','Mayan scribe','Mayan astronomer-priest',
    'medieval serf','villein','yeoman farmer','free man','bondsman','thrall',
    'medieval merchant','guildsman','guild apprentice','guild journeyman','guild master',
    'wandering friar','pardoner (Chaucer)','summoner (Chaucer)','reeve','franklin (yeoman)',
    'court fool (historical)','lord of misrule','May king','Green Man figure',
    'jack-of-all-trades','renaissance man','polymath','universal genius',
    'salon hostess','bluestocking','learned lady','patroness of the arts',
    // More villain archetypes
    'puppetmaster villain','string-puller','shadow broker','information broker villain',
    'crime kingpin','mob boss','Mafia Don','Triad Dragon Head','Yakuza oyabun',
    'cartel leader','narco boss','drug lord','black market queen','contraband emperor',
    'extortion ring leader','protection racket boss','loan shark','numbers runner boss',
    'fence (criminal)','receiver of stolen goods','chop shop boss','car theft ring leader',
    'art thief mastermind','jewel thief','heist planner','caper mastermind',
    'con man supreme','long-con artist','Ponzi schemer','pyramid scheme architect',
    'catfisher','romance scammer','identity thief','deepfake artist (criminal)',
    // More fairytale / folklore
    'Baba Yaga','Baba Yaga\'s chicken-legged house','Vasilisa the Beautiful','Firebird guardian',
    'Koschei the Deathless','Leshy (forest spirit)','Domovoi (house spirit)','Rusalka',
    'Kikimora','Dvorovoi (yard spirit)','Dvorovoi','Bannik (bathhouse spirit)',
    'Cailleach (winter hag)','Selkie bride','Kelpie rider','nuckelavee','bean-nighe',
    'Sluagh (restless dead)','each-uisge','Brownie (helpful)','boggart (mischievous)',
    'Jenny Greenteeth','Peg Powler','Black Annis','Rawhead and Bloody Bones',
    'Tom Tit Tot','Rumpelstiltskin variant','name-guessing demon',
    'Three Billy Goats Gruff troll','Troll wife','Mountain troll','Cave troll',
    'Snow Queen','Ice King','Frost Giant\'s daughter','Winter spirit',
    'Summer King','Green Knight (Arthurian)','the Fisher King','the Grail Knight',
    'Morgan le Fay','Morgause','Nimue (Lady of the Lake)','Bedivere','Gawain',
    'Sir Lancelot','Sir Percival','Sir Galahad','Sir Bors','Sir Lamorak',
    // Modern archetypes (more)
    'washed-up pop star','one-hit wonder','comeback artist','nostalgia act',
    'underground legend','cult film actor','b-movie star','exploitation film hero',
    'true crime podcaster','amateur sleuth','armchair detective','cold case reopener',
    'doomsday prepper','bunker builder','off-grid pioneer','survivalist hermit',
    'competitive hoarder','extreme couponer','thrift store flipper','dumpster diver',
    'freegan philosopher','zero waste activist','minimalist extremist','tiny home guru',
    'van life influencer','perpetual traveler','country hopper','passport collector',
    'visa run veteran','immigration limbo dweller','stateless wanderer',
    'time zone hopper','jet lag connoisseur','airport lounge philosopher',
    'frequent flyer elite','airline points millionaire','hotel points hoarder',
    'digital nomad burnout','remote work refugee','coworking space regular',
    // More historical / military character types
    'hedge knight','free lance (medieval)','sword for hire','camp follower',
    'vivandière (camp vendor)','sutler (army merchant)','regimental surgeon',
    'military chaplain','war correspondent (historical)','war poet',
    'battlefield nurse (historical)','dispatch rider (military)',
    'cavalry scout','light dragoon','hussar','lancer','cuirassier',
    'janissary recruit','sipahi cavalryman','cataphract',
    // More improv-useful archetypes
    'accidental hero','unlikely champion','wrong-place-right-time witness',
    'reluctant expert','only sane person in the room','voice of reason (ignored)',
    'devil\'s advocate','contrarian intellectual','professional skeptic',
    'late bloomer','second-chance protagonist','comeback kid',
    'burnout survivor','debt-ridden dreamer','gig worker protagonist',
  ],

  timePeriods: [
    // More specific ancient sub-periods
    'Early Dynastic Period Egypt','First Intermediate Period','Second Intermediate Period',
    'Third Intermediate Period','Saite Period','Ptolemaic Period',
    'Uruk Period (Mesopotamia)','Early Dynastic Mesopotamia','Ur III Period',
    'Old Babylonian Period','Kassite Period','Neo-Assyrian Empire',
    'Neo-Babylonian Empire','Achaemenid Period','Seleucid Period',
    'Minoan Crete','Mycenaean Greece','Greek Dark Ages','Geometric Period Greece',
    'Orientalizing Period Greece','Archaic Period Greece','Persian Wars era',
    'Peloponnesian War era','Macedonian conquest era','Diadochi Wars era',
    'Roman Kingdom','Early Republic (Rome)','Middle Republic','Late Republic',
    'Principate (Rome)','Dominate (Rome)','Western decline (Rome)','Byzantine flourishing',
    'Justinian\'s era','Macedonian dynasty (Byzantine)','Komnenian era','Palaiologan era',
    // Medieval sub-periods
    'Migration period (400-700 CE)','Merovingian Frankia','Carolingian Renaissance',
    'Viking raids era','Danelaw period','Norman England','Angevin England',
    'Plantagenet era','Capetian France','Valois France','Hundred Years War period',
    'Black Death years','Conciliar movement era','Great Schism period',
    'High Crusade era','Children\'s Crusade era','Crusader states period',
    'Mongol Il-Khanate','Mongol Yuan China','Blue Horde era','White Horde era',
    'Mamluk Sultanate era','Delhi Sultanate era','Vijayanagara Empire era',
    'Tsin dynasty','Tang dynasty','Song dynasty','Southern Song period',
    'Kamakura period Japan','Muromachi period','Sengoku period','Azuchi-Momoyama',
    'Joseon Dynasty early','Yi dynasty early','Three Kingdoms Korea','Goryeo period',
    // Early modern sub-periods
    'Italian Renaissance (quattrocento)','Italian Renaissance (cinquecento)',
    'Northern Renaissance (German)','Northern Renaissance (Flemish)','Northern Renaissance (Dutch)',
    'Elizabethan England','Jacobean England','Caroline England','Interregnum',
    'Restoration England','Glorious Revolution era','Queen Anne era',
    'Age of Louis XIV','Regency of Philippe d\'Orléans','Louis XV era','Louis XVI era',
    'Seven Years War era','War of Austrian Succession era','War of Spanish Succession',
    'Dutch Golden Age','Spanish Golden Age','siglo de oro','Baroque Spain',
    'Thirty Years War','Peace of Westphalia era','post-Westphalia order',
    'Age of Reason (1680-1780)','Scottish Enlightenment','French Enlightenment',
    'American founding era','Constitutional Convention era','Federalist era',
    'Age of Napoleon','Continental System era','Peninsular War era','Waterloo aftermath',
    'Concert of Europe era','Metternich\'s Europe','Spring of Nations 1848',
    // 19th century sub-periods
    'Regency period (England)','Victorian early','Victorian mid','Victorian late',
    'Edwardian England','Gilded Age USA','Progressive Era USA','Robber Baron era',
    'Belle Époque France','Third Republic France','Commune era France',
    'Bismarckian Germany','Wilhelmine Germany','Imperial Germany',
    'Meiji Restoration','Meiji Japan (1868-1912)','Taisho Democracy','early Showa',
    'Scramble for Africa','high imperialism','Pax Britannica','Pax Americana (early)',
    'Abolition era','Reconstruction era','Jim Crow era','Gilded Age South',
    'Old West','cattle drive era','homesteader era','range war era',
    'Gold Rush (California)','Gold Rush (Klondike)','Gold Rush (Australia)',
    // Early 20th century sub-periods
    'Edwardian golden summer','pre-war European order','July Crisis 1914',
    'opening months of WW1','trench stalemate era','home front WW1','total war mobilization',
    'Versailles settlement era','Weimar Republic stability','Weimar hyperinflation',
    'Jazz Age peak (1925-29)','stock market boom','Black Tuesday aftermath',
    'early Depression','Dust Bowl peak','New Deal implementation','late Depression',
    'Appeasement era','Anschluss era','Phoney War','Dunkirk era','Battle of Britain',
    'blitz on London','Operation Barbarossa era','Stalingrad turning point',
    'D-Day invasion','liberation of Europe','Pacific island-hopping era',
    'Manhattan Project era','early atomic era','Hiroshima aftermath',
    // Cold War sub-periods
    'Berlin Blockade era','Korean War years','McCarthy era','Eisenhower era',
    'Sputnik shock era','Kennedy presidency','Johnson Great Society era',
    'Nixon era','détente era','Ford-Carter era','Reaganomics era',
    'Star Wars defense era','Gorbachev glasnost','perestroika era',
    'Solidarity movement','Velvet Revolution era','Berlin Wall fall era',
    'Soviet dissolution era','1991 coup attempt era','post-Soviet chaos',
    'Yeltsin era Russia','Clinton prosperity era','NAFTA era','dot-com IPO era',
    // Recent and contemporary sub-periods
    'post-9/11 security state','PATRIOT Act era','Guantanamo era','Abu Ghraib era',
    'Iraq surge era','Arab Spring first wave','Arab Spring aftermath','Syrian civil war era',
    'Obama first term','Obama second term','Tea Party era','Occupy era',
    'European debt crisis years','austerity Europe','Greek crisis years',
    'Brexit campaign','Brexit referendum','Brexit implementation','post-Brexit UK',
    'Trump era','Biden era','polarization era','post-truth era','disinformation era',
    'COVID first wave','COVID delta wave','COVID omicron wave','post-pandemic adjustment',
    'Ukraine war era','energy crisis 2022','inflation surge 2022','rate hike cycle',
    'AI chatbot revolution','generative AI era','AGI debate era',
    // Future sub-periods (more specific)
    'near-term future (5 years)','mid-term future (25 years)','long-term future (100 years)',
    'post-fossil fuel transition','renewable energy civilization','fusion power era',
    'first commercial moon base','lunar gateway station era','first Mars landing',
    'Mars settlement era','multi-planetary civilization','asteroid belt colonization',
    'outer planet exploration era','first interstellar probe launch','first signals from exoplanets',
    'post-scarcity economics era','universal basic income era','post-work civilization',
    'longevity escape velocity era','partial life extension era','full biological immortality',
    'human-AI merger era','neural lace era','brain-computer interface mainstream',
    'digital-physical merger','ambient computing era','invisible tech era',
    'climate stabilization era','great biodiversity restoration','de-extinction era',
    'rewilded continents era','ocean restoration era','atmospheric carbon removal era',
    // Fictional time periods (more)
    'Year of the Dragon (fantasy)','Year of Reckoning','Year of the Sword','Year of the Comet',
    'the Long Winter (fantasy)','the Long Summer','the Age of Ash','the Age of Ice',
    'the Quiet Years','the Years of Silence','the Forgotten Age','the Hidden Era',
    'before the Sundering','after the Sundering','pre-Cataclysm','post-Cataclysm',
    'the First Age (Tolkien style)','the Second Age','the Third Age','the Fourth Age',
    'the Age before Memory','the Time before Time','before the gods woke',
    'when dragons ruled','when men first spoke','when magic was young',
    'the Gilded Age of Sorcery','the Prohibition of Magic era','the Dark Magic Renaissance',
    'the Machine Wars era (fantasy)','the Clockwork Rebellion','the Steam Uprising',
    'the Silent Empire era','the Great Diaspora','the Stellar Refuge era',
    // More times of day / moments
    'the small hours','the graveyard shift','the dog watch','the morning watch',
    'the forenoon watch','the afternoon watch','the first dog watch','the second dog watch',
    'an ordinary Tuesday','an extraordinary Monday','the last day of term',
    'the first day of the rest of your life','that pivotal Thursday afternoon',
    'the morning everything changed','the day before the wedding','the day after the funeral',
    'mid-heist','in the getaway moment','when the timer hits zero',
    'the exact moment of impact','the pause before the storm breaks',
    'three seconds before everything goes wrong','the instant of hesitation',
    // Roman crisis periods
    'Year of Four Emperors','Year of Five Emperors','Year of Six Emperors',
    'Crisis of the Third Century','First Triumvirate era','Second Triumvirate era',
    'the Gracchi reforms era','Marian reforms era','Sullan dictatorship',
    'Social War era (Rome)','Catiline conspiracy era',
    // British / European crisis periods
    'the Anarchy (England 1135-1153)','the Fronde','the Time of Troubles (Russia)',
    'the Stuarts\' Exclusion Crisis','the Popish Plot era','the Glorious Revolution year',
    'the Jacobite rising era','the Forty-Five era','the Gordon Riots era',
    // Chinese historical micro-periods
    'Boxer Rebellion era','Treaty Port era China','Self-Strengthening Movement',
    'Hundred Days Reform','May Fourth Movement era','warlord era China',
    'Nanjing Decade','Long March era','Second Sino-Japanese War era',
    'Great Leap Forward era','Cultural Revolution era','Gang of Four era',
    'Reform and Opening era','one-child policy era',
    // Japanese micro-periods
    'party democracy era Japan','militarist Japan era',
    'MacArthur occupation Japan','Japanese economic miracle era',
    'bubble economy Japan','lost decade Japan','Heisei stagnation era',
    // Indian sub-periods
    'Chola Empire era','Pallava era','Chalukya era',
    'Maratha Empire era','Sikh Empire era','Bengal Renaissance era',
    'Swadeshi movement era','Salt March era','Partition era',
    // Islamic / African historical
    'Umayyad golden age','Abbasid golden age','Fatimid Caliphate era',
    'Almohad era','Almoravid era','Nasrid Kingdom era',
    'Sokoto Caliphate era','Mali Empire era','Songhai Empire era',
    'Kanem-Bornu era','Great Zimbabwe era','Zulu Kingdom era',
    'Ashanti Empire era','Benin Kingdom era','Kingdom of Dahomey era',
    // Ages defined by technology
    'age of sail','age of steam','age of oil','age of the atom',
    'age of the algorithm','age of synthetic biology','age of quantum computing',
    'age of oral tradition','age of scribes','age of manuscripts',
    'age of print','age of mass media','age of the internet',
    'before electricity','before printing','before agriculture',
    // Narrative / story-focused periods
    'the brief golden age','the long decadence','the sudden collapse',
    'the slow recovery','the second flowering','the time of migrations',
    'the years of plenty','the years of want','the days of wonder',
    'the nights of terror','the chapter before the fall','the prologue to war',
    'the interlude between empires','the gap in the records',
    'the golden age before the fall','the morning after the coup',
    'the night before the revolution','the hour of reckoning',
    'the moment of unmasking','when the truth came out',
    'the last generation before the change',
    // More fictional ages
    'the Fifth Age (fantasy)','the Sixth Age (fantasy)','the Age of Wonders',
    'the Ember Age','the Bone Age','the Silver Age (fantasy)',
    'the Twilight Age','the Dawn Age','the Age of Myth',
    'the Age of Dominion','the Age of Ruin','the Age of Restoration',
    'the Age of Exile','the Age of Return','the Age of the Covenant',
    'the Age of Shattering','the Age of Binding','the Age of Unraveling',
    'the Age of Silence','the Age of Noise','the Age of Questions',
    'the Age of Answers','the Age of Forgetting','the Age of Remembrance',
  ],

};

// ---------------------------------------------------------------------------
// File writing template
// ---------------------------------------------------------------------------
function writeDataFile(category, globalVarName, words) {
  const unique = [...new Set(words)];
  const lines = [];
  const chunkSize = 10;
  for (let i = 0; i < unique.length; i += chunkSize) {
    const chunk = unique.slice(i, i + chunkSize).map(w => JSON.stringify(w));
    lines.push('    ' + chunk.join(','));
  }
  return `(function (root) {\n  var words = [\n${lines.join(',\n')}\n  ];\n\n  if (typeof module !== 'undefined' && module.exports) {\n    module.exports = words;\n  } else {\n    root.${globalVarName} = words;\n  }\n}(typeof window !== 'undefined' ? window : this));\n`;
}

const globalNames = {
  places:         'WORDS_PLACES',
  transportation: 'WORDS_TRANSPORTATION',
  food:           'WORDS_FOOD',
  objects:        'WORDS_OBJECTS',
  animals:        'WORDS_ANIMALS',
  occupations:    'WORDS_OCCUPATIONS',
  emotions:       'WORDS_EMOTIONS',
  actions:        'WORDS_ACTIONS',
  characters:     'WORDS_CHARACTERS',
  timePeriods:    'WORDS_TIME_PERIODS',
};

const dataDir = path.join(__dirname, '..', 'data');

Object.keys(globalNames).forEach(cat => {
  const file = path.join(dataDir, cat + '.js');
  const existing = require(file);  // returns the raw array
  const extra = additions[cat] || [];
  const combined = [...existing, ...extra];
  const unique = [...new Set(combined)];
  const content = writeDataFile(cat, globalNames[cat], unique);
  fs.writeFileSync(file, content, 'utf8');
  console.log(`${cat}: ${unique.length} unique words`);
});

console.log('\nDone. Run `npm test` to verify.');
